### ISSUE TITLE
AMD GPU Support

### ISSUE THREAD

**Issue by shintaro-iwasaki** [pytorch/FBGEMM#1266]
This issue is to keep track of AMD GPU support. Note that performance optimization is out of scope of this tracker since we haven't encountered a catastrophic performance bug (or it becomes endless). The list will be updated.

## Enablement/Functionality
  - [x] Integrate hipification logic (#1102)
  - [ ] Fix a UVM feature (see #1142)

## Tests
  - [x] Enable build CI with ROCm (#1161)
  - [x] Enable execution CI using AMD GPUs (#1193, #1196)

## Installation
  - [ ] Release stable/nightly packages for AMD GPUs
  - [ ] Enrich building instructions for AMD GPUs
